version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: example
      MARIADB_PASSWORD: example
    ports:
      - "3306:3306"