apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mercure-example-chat.fullname" . }}
  labels:
    {{- include "mercure-example-chat.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  hubUrl: {{ .Values.hubUrl | quote }}
  cookieDomain: {{ .Values.cookieDomain | quote }}
  messageUriTemplate: {{ .Values.messageUriTemplate | quote }}
