apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mercure-example-chat.fullname" . }}
  labels:
    {{- include "mercure-example-chat.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"    
type: Opaque
data:
  jwtKey: {{ .Values.jwtKey | b64enc | quote }}
